#服务端口
server:
  port: 8089

#服务注册中心
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yyxiao/MyBootConfig.git
          search-paths: /**
          username: ******
          password: ******
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
