#服务端口
server:
  port: 8089

#服务注册中心
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yyxiao/MyBootConfig.git
          search-paths: /**
      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
#      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:1111/eureka/
#    security:
#      basic:
#        user: test
#        password: test