# 默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，
# 所以我们需要禁用它的客户端注册行为，只需要在application.yml中问增加如下配置：
# yml比properties可读性高，建议spring boot搭建尽量使用yml
server:
  port: 1111

# security权限安全控制
#security:
#  user:
#    name: test
#    password: test

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/