#hystrix
#服务调用超时时间
hystrix:
  timeoutInMillions: 3000

server:
  port: 8101

spring:
  application:
    name: hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
  instance:
    instance-id: hystrix服务-8101
