db:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
  username: root
  password: root

server:
  port: 2222

#thymeleaf start
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
#spring.application.name属性，我们可以指定微服务的名称后续在调用的时候只需要使用该名称就可以进行服务的访问。
  application:
    name: myboot-service
#开发时关闭缓存,不然没法看到实时页面
    cache: false
#默认thymeleaf的前缀
    #prefix: /templates/
#默认thymeleaf的后缀
    #suffix: .html
#thymeleaf end

#eureka.client.serviceUrl.defaultZone属性对应服务注册中心的配置内容，指定服务注册中心的位置。
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# 日志logback管理
logback:
  logdir: /Users/xiaoyy/data/logs/myBoot/provider
  appname: MyBoot-provider