server:
  port: 4332

spring:
  application:
    name: ribbon
#将consumer注册到eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://test:test@localhost:1111/eureka/
#  instance:
#    prefer-ip-address: true